### PR TITLE
Added graphcool-lib dependency

### PR DESCRIPTION
**Pull request by dervos**
You can actually use any dependency available on npmjs. You just have to reference it.

### CODE REVIEW

**Comment by kbrandwijk** [comment]
I think the approach from https://github.com/graphcool-examples/functions/pull/28 is more generic. It follows the normal local workflow of `npm install`-ing a dependency, and `wt-cli` automatically picking them up.

**Comment by dervos** [comment]
Just noticed #28, apologies for the duplicate PR.

However, using the cli dependency argument seems more clean and verbose.

**Comment by kbrandwijk** [comment]
I think both options could end up in there, there's also `wt modules add ...` to make a npm module available to all webtasks in your container. I usually follow the `npm install` route because that's needed to run the script locally, which I usually do before deploying it.

**Comment by kbrandwijk** [comment]
Also, it's the recommended method per the webtask.io documentation: https://webtask.io/docs/modules

**Comment by dervos** [comment]
You're right. When using multiple dependencies, a `package.json` file is needed. It's also better documented and is in line with what people are already used to.

Perhaps a we could add a note referring to the documentation you mentioned, allowing people to decide for themselves.

**Comment by kbrandwijk** [comment]
I'll update my PR accordingly.

**Comment by dervos** [comment]
@kbrandwijk Cool, closing this PR. Thanks!

**Pull request closed without merging**
