### PR TITLE
TicTacToe gameserver example

### PR DESCRIPTION
**Pull request by kbrandwijk**
A TicTacToe gameserver, fully implemented in the Graphcool backend. Demonstrates the use of permission queries, request pipeline hooks, API calls using `graphql-request` and server side subscriptions. Will also be used as a backend for a Unity3D frontend.

### CODE REVIEW

**Comment by kbrandwijk** [comment]
PR Ready

**Comment by marktani** [comment]
Thanks so much for this! I will take the time to review your example in the coming days 🙂

**Comment by marktani** [comment]
Looks like the position is 1-based, which I didn't know. I ran this mutation

```graphql
mutation b {
  createMove(gameId: "cj5fh811qe71z019670g580si", position: 0) {
    game
    {
      gameState{
        board
        winner
        turn
        status
      }
    }
  }
}
```

and it behave as follows

* no player symbol was added
* a new computer symbol was added

Can we add a function to `TRANSFORM_ARGUMENTS` that validates the given position is 1-9 and still free?

**Comment by kbrandwijk** [comment]
Thank you for you review. The 'still free' part is taken care of by the PQ. I'll add the range validation to the RP, as that's the easiest place to implement it.

**Comment by marktani** [comment]
Thanks for yet another great example, @kbrandwijk :tada:

**Pull request merged**
